// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3tNiB9ElfjQqA-OxoAF6uWY4OG5Mnmu4',
    appId: '1:226340103987:web:bf60952aaf87223d2b0046',
    messagingSenderId: '226340103987',
    projectId: 'o-task-manager-nf',
    authDomain: 'o-task-manager-nf.firebaseapp.com',
    storageBucket: 'o-task-manager-nf.firebasestorage.app',
    measurementId: 'G-EBKNM8MEHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWjb3-2AAYOZYxgj2npAUYKMTuMfKS8A0',
    appId: '1:226340103987:android:2108d4322c3bc9462b0046',
    messagingSenderId: '226340103987',
    projectId: 'o-task-manager-nf',
    storageBucket: 'o-task-manager-nf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA68VRKzg98jtw2Qq5fZ49l3s4M4LJ8ekQ',
    appId: '1:226340103987:ios:a5862b78c304ac352b0046',
    messagingSenderId: '226340103987',
    projectId: 'o-task-manager-nf',
    storageBucket: 'o-task-manager-nf.firebasestorage.app',
    iosBundleId: 'com.example.firebasePushLocalNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA68VRKzg98jtw2Qq5fZ49l3s4M4LJ8ekQ',
    appId: '1:226340103987:ios:a5862b78c304ac352b0046',
    messagingSenderId: '226340103987',
    projectId: 'o-task-manager-nf',
    storageBucket: 'o-task-manager-nf.firebasestorage.app',
    iosBundleId: 'com.example.firebasePushLocalNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3tNiB9ElfjQqA-OxoAF6uWY4OG5Mnmu4',
    appId: '1:226340103987:web:81b4f6b25c944e6d2b0046',
    messagingSenderId: '226340103987',
    projectId: 'o-task-manager-nf',
    authDomain: 'o-task-manager-nf.firebaseapp.com',
    storageBucket: 'o-task-manager-nf.firebasestorage.app',
    measurementId: 'G-B8WLRC6CHT',
  );
}
